version: '3.10'
services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - postgres

  postgres_database:
    container_name: postgres_container
    image: "bitnami/postgresql:latest"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "owrendb"
    ports:
      - "5432:5432"
    volumes:
      - "test-data:/var/lib/postgresql/data"
    networks:
      - "postgres"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "5050:80"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    networks:
      - "postgres"

volumes:
  test-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
