version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  pg_db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: voice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_container:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin

volumes:
  postgres_container:
  pgadmin4: