# Generated by Django 4.1.7 on 2023-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
