# Generated by Django 4.1.6 on 2023-02-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_interest_name_alter_interest_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(max_length=100000)),
                ('image_under_title', models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d')),
                ('image_in_post', models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('interests', models.ManyToManyField(blank=True, to='app.interest')),
            ],
        ),
    ]
