# Generated by Django 4.1.7 on 2023-02-16 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/1.png', null=True, upload_to='profiles/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('interests', models.ManyToManyField(blank=True, to='app.interest')),
                ('skills', models.ManyToManyField(blank=True, to='app.skill')),
            ],
            options={
                'verbose_name': 'Pofile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(max_length=100000)),
                ('image_under_title', models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d')),
                ('image_in_post', models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.profile')),
                ('interests', models.ManyToManyField(blank=True, to='app.interest')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authentication.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('image_in_post', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('interests', models.ManyToManyField(blank=True, to='app.interest')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_created'],
            },
        ),
    ]
