# Generated by Django 4.1.6 on 2023-02-08 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/1.png', null=True, upload_to='profiles/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Pofile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_date'],
            },
        ),
    ]
