# Generated by Django 4.1.7 on 2023-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_articles_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='third_image',
        ),
        migrations.AddField(
            model_name='post',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=555, unique=True),
        ),
    ]
