# Generated by Django 4.1.7 on 2023-02-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_comment_text_alter_news_body_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_in_post',
            new_name='title_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_in_post',
        ),
        migrations.RemoveField(
            model_name='news',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_under_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='third_image',
        ),
    ]
