# Generated by Django 4.1.6 on 2023-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%M/%d'),
        ),
    ]
