# Generated by Django 4.1.7 on 2023-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_post_second_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_descleription',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
