# Generated by Django 4.1.7 on 2023-02-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_post_meta_description_post_meta_descleription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_descleription',
        ),
    ]
