# Generated by Django 4.1.7 on 2023-02-16 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_post'),
        ('authentication', '0010_remove_post_meta_descleription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('slyg', models.SlugField(max_length=255, unique=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('image_in_post', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%M/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('interests', models.ManyToManyField(blank=True, to='app.interest')),
            ],
        ),
    ]
